[Icon Theme]
Name=Tango
Comment=The icons the PathNoWorks desktop uses, from the Tango icon theme 0.8.90
Directories=16x16/actions,16x16/apps,16x16/categories,16x16/devices,16x16/emblems,16x16/mimetypes,16x16/places,16x16/status,22x22/actions,22x22/apps,22x22/categories,22x22/devices,22x22/emblems,22x22/mimetypes,22x22/places,22x22/status,32x32/actions,32x32/apps,32x32/categories,32x32/devices,32x32/emblems,32x32/mimetypes,32x32/places,32x32/status,scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/emblems,scalable/mimetypes,scalable/places,scalable/status

[16x16/actions]
Size=16
Type=Fixed
Context=actions

[16x16/apps]
Size=16
Type=Fixed
Context=apps

[16x16/categories]
Size=16
Type=Fixed
Context=categories

[16x16/devices]
Size=16
Type=Fixed
Context=devices

[16x16/emblems]
Size=16
Type=Fixed
Context=emblems

[16x16/mimetypes]
Size=16
Type=Fixed
Context=mimetypes

[16x16/places]
Size=16
Type=Fixed
Context=places

[16x16/status]
Size=16
Type=Fixed
Context=status

[22x22/actions]
Size=22
Type=Fixed
Context=actions

[22x22/apps]
Size=22
Type=Fixed
Context=apps

[22x22/categories]
Size=22
Type=Fixed
Context=categories

[22x22/devices]
Size=22
Type=Fixed
Context=devices

[22x22/emblems]
Size=22
Type=Fixed
Context=emblems

[22x22/mimetypes]
Size=22
Type=Fixed
Context=mimetypes

[22x22/places]
Size=22
Type=Fixed
Context=places

[22x22/status]
Size=22
Type=Fixed
Context=status

[32x32/actions]
Size=32
Type=Fixed
Context=actions

[32x32/apps]
Size=32
Type=Fixed
Context=apps

[32x32/categories]
Size=32
Type=Fixed
Context=categories

[32x32/devices]
Size=32
Type=Fixed
Context=devices

[32x32/emblems]
Size=32
Type=Fixed
Context=emblems

[32x32/mimetypes]
Size=32
Type=Fixed
Context=mimetypes

[32x32/places]
Size=32
Type=Fixed
Context=places

[32x32/status]
Size=32
Type=Fixed
Context=status

[scalable/actions]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=actions

[scalable/apps]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=apps

[scalable/categories]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=categories

[scalable/devices]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=devices

[scalable/emblems]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=emblems

[scalable/mimetypes]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=mimetypes

[scalable/places]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=places

[scalable/status]
Size=32
Type=Scalable
MinSize=8
MaxSize=512
Context=status
